### ISSUE TITLE
GIMP_AppImage-git-2.99.1-20200401-x86_64 not starting any more

### ISSUE THREAD

**Issue by mzannoni** [aferrero2707/gimp-appimage#47] opened 2020-04-09 22:18 UTC
I've been using the version just before in Ubuntu 18.04 and it works quite fine.

I've then downloaded the `20200401` version, but it's not starting any more.

Please, find below the output from the terminal:
```
bill@yoda:GIMP$ ./GIMP_AppImage-git-2.99.1-20200401-x86_64.AppImage 
DIR: /tmp/.mount_GIMP_ArQDnFT
AILIBDIR=/tmp/tmp.IcJz3WFAgh
deleting /tmp/tmp.IcJz3WFAgh/libxcb-dri3.so*
System stdc++ library: "/usr/lib/x86_64-linux-gnu/libstdc++.so.6"
System stdc++ library version: "3.4.25"
Bundled stdc++ library version: "3.4.22"
Newest stdc++ library version: "3.4.25"
Using system stdc++ library
atomiclib: /usr/lib/x86_64-linux-gnu/libatomic.so.1
Checking versions of library "libfontconfig"
  system library: "/usr/lib/x86_64-linux-gnu/libfontconfig.so.1.10.1" (libfontconfig.so.1.10.1)
  system library version: 1.10.1
  ailib: "/tmp/.mount_GIMP_ArQDnFT/usr/lib/libfontconfig.so.1.11.1"
  bundled library: "/tmp/.mount_GIMP_ArQDnFT/usr/lib/libfontconfig.so.1.11.1" (libfontconfig.so.1.11.1)
  bundled library version: 1.11.1
  newest library version: "1.11.1"
Checking versions of library "libfreetype"
  system library: "/usr/lib/x86_64-linux-gnu/libfreetype.so.6.15.0" (libfreetype.so.6.15.0)
  system library version: 6.15.0
  ailib: "/tmp/.mount_GIMP_ArQDnFT/usr/lib/libfreetype.so.6.16.1"
  bundled library: "/tmp/.mount_GIMP_ArQDnFT/usr/lib/libfreetype.so.6.16.1" (libfreetype.so.6.16.1)
  bundled library version: 6.16.1
  newest library version: "6.16.1"
GTK_PATH=/tmp/.mount_GIMP_ArQDnFT/usr/lib/gtk-2.0
GTK_IM_MODULE_FILE=/tmp/.mount_GIMP_ArQDnFT/usr/lib/gtk-2.0:/tmp/.mount_GIMP_ArQDnFT/usr/lib/gtk-2.0
PANGO_LIBDIR=/tmp/.mount_GIMP_ArQDnFT/usr/lib
BABL_PATH /tmp/.mount_GIMP_ArQDnFT/usr/lib/babl-0.1
GEGL_PATH /tmp/.mount_GIMP_ArQDnFT/usr/lib/gegl-0.4
python=/tmp/.mount_GIMP_ArQDnFT/usr/bin/python3
python3=/tmp/.mount_GIMP_ArQDnFT/usr/bin/python3
/tmp/.mount_GIMP_ArQDnFT/usr/bin/python=/tmp/.mount_GIMP_ArQDnFT/usr/bin/python3
:Python:E::py::python3:
GIMP3_PLUGINDIR: /tmp/tmp.IcJz3WFAgh/gimp/2.99
/tmp/.mount_GIMP_ArQDnFT/apprun-helper.sh: line 179: /tmp/.mount_GIMP_ArQDnFT/startup_scripts/*.sh: No such file or directory
Input parameters: ""

Input File: 
/bin/bash: /tmp/tmp.IcJz3WFAgh/libtinfo.so.5: no version information available (required by /bin/bash)
	linux-vdso.so.1 (0x00007ffff3de5000)
	libgimpwidgets-3.0.so.0 => /tmp/tmp.IcJz3WFAgh/libgimpwidgets-3.0.so.0 (0x00007fa59a184000)
	libgtk-3.so.0 => /tmp/tmp.IcJz3WFAgh/libgtk-3.so.0 (0x00007fa59986d000)
	libgdk-3.so.0 => /tmp/tmp.IcJz3WFAgh/libgdk-3.so.0 (0x00007fa59957f000)
	libatk-1.0.so.0 => /tmp/tmp.IcJz3WFAgh/libatk-1.0.so.0 (0x00007fa599359000)
	libcairo-gobject.so.2 => /tmp/tmp.IcJz3WFAgh/libcairo-gobject.so.2 (0x00007fa599150000)
	libgimpconfig-3.0.so.0 => /tmp/tmp.IcJz3WFAgh/libgimpconfig-3.0.so.0 (0x00007fa598f37000)
	libgimpmath-3.0.so.0 => /tmp/tmp.IcJz3WFAgh/libgimpmath-3.0.so.0 (0x00007fa598d30000)
	libgimpthumb-3.0.so.0 => /tmp/tmp.IcJz3WFAgh/libgimpthumb-3.0.so.0 (0x00007fa598b26000)
	libgimpcolor-3.0.so.0 => /tmp/tmp.IcJz3WFAgh/libgimpcolor-3.0.so.0 (0x00007fa59890f000)
	libgimpmodule-3.0.so.0 => /tmp/tmp.IcJz3WFAgh/libgimpmodule-3.0.so.0 (0x00007fa598709000)
	libgimpbase-3.0.so.0 => /tmp/tmp.IcJz3WFAgh/libgimpbase-3.0.so.0 (0x00007fa5984db000)
	libappstream-glib.so.8 => /tmp/tmp.IcJz3WFAgh/libappstream-glib.so.8 (0x00007fa59827b000)
	libgdk_pixbuf-2.0.so.0 => /tmp/tmp.IcJz3WFAgh/libgdk_pixbuf-2.0.so.0 (0x00007fa598053000)
	libpangocairo-1.0.so.0 => /tmp/tmp.IcJz3WFAgh/libpangocairo-1.0.so.0 (0x00007fa597e45000)
	libpangoft2-1.0.so.0 => /tmp/tmp.IcJz3WFAgh/libpangoft2-1.0.so.0 (0x00007fa597c2f000)
	libpango-1.0.so.0 => /tmp/tmp.IcJz3WFAgh/libpango-1.0.so.0 (0x00007fa5979e9000)
	libcairo.so.2 => /tmp/tmp.IcJz3WFAgh/libcairo.so.2 (0x00007fa5976d2000)
	libpixman-1.so.0 => /tmp/tmp.IcJz3WFAgh/libpixman-1.so.0 (0x00007fa597429000)
	libfontconfig.so.1 => /tmp/tmp.IcJz3WFAgh/libfontconfig.so.1 (0x00007fa5971e8000)
	libexpat.so.1 => /tmp/tmp.IcJz3WFAgh/libexpat.so.1 (0x00007fa596fbe000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fa596db7000)
	libfreetype.so.6 => /tmp/tmp.IcJz3WFAgh/libfreetype.so.6 (0x00007fa596b0f000)
	libharfbuzz.so.0 => /tmp/tmp.IcJz3WFAgh/libharfbuzz.so.0 (0x00007fa596872000)
	libpng16.so.16 => /tmp/tmp.IcJz3WFAgh/libpng16.so.16 (0x00007fa596640000)
	libxcb-shm.so.0 => /tmp/tmp.IcJz3WFAgh/libxcb-shm.so.0 (0x00007fa59643c000)
	libxcb.so.1 => /tmp/tmp.IcJz3WFAgh/libxcb.so.1 (0x00007fa596214000)
	libxcb-render.so.0 => /tmp/tmp.IcJz3WFAgh/libxcb-render.so.0 (0x00007fa596006000)
	libXrender.so.1 => /tmp/tmp.IcJz3WFAgh/libXrender.so.1 (0x00007fa595dfb000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fa595ac3000)
	libXext.so.6 => /tmp/tmp.IcJz3WFAgh/libXext.so.6 (0x00007fa5958b1000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa5956a9000)
	libgegl-0.4.so.0 => /tmp/tmp.IcJz3WFAgh/libgegl-0.4.so.0 (0x00007fa5953d2000)
	libgegl-npd-0.4.so => /tmp/tmp.IcJz3WFAgh/libgegl-npd-0.4.so (0x00007fa5951ca000)
	libjson-glib-1.0.so.0 => /tmp/tmp.IcJz3WFAgh/libjson-glib-1.0.so.0 (0x00007fa594fa3000)
	libbabl-0.1.so.0 => /tmp/tmp.IcJz3WFAgh/libbabl-0.1.so.0 (0x00007fa594cb3000)
	libgio-2.0.so.0 => /tmp/tmp.IcJz3WFAgh/libgio-2.0.so.0 (0x00007fa594908000)
	libgmodule-2.0.so.0 => /tmp/tmp.IcJz3WFAgh/libgmodule-2.0.so.0 (0x00007fa594704000)
	libselinux.so.1 => /tmp/tmp.IcJz3WFAgh/libselinux.so.1 (0x00007fa5944dd000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fa5942c2000)
	libmount.so.1 => /tmp/tmp.IcJz3WFAgh/libmount.so.1 (0x00007fa59407f000)
	liblcms2.so.2 => /tmp/tmp.IcJz3WFAgh/liblcms2.so.2 (0x00007fa593e25000)
	libgexiv2.so.2 => /tmp/tmp.IcJz3WFAgh/libgexiv2.so.2 (0x00007fa593c04000)
	libexiv2.so.26 => /tmp/tmp.IcJz3WFAgh/libexiv2.so.26 (0x00007fa59360c000)
	libarchive.so.13 => /tmp/tmp.IcJz3WFAgh/libarchive.so.13 (0x00007fa59334d000)
	libcrypto.so.10 => /tmp/tmp.IcJz3WFAgh/libcrypto.so.10 (0x00007fa592eea000)
	liblzma.so.5 => /tmp/tmp.IcJz3WFAgh/liblzma.so.5 (0x00007fa592cc4000)
	libbz2.so.1 => /tmp/tmp.IcJz3WFAgh/libbz2.so.1 (0x00007fa592ab4000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa592897000)
	libxml2.so.2 => /tmp/tmp.IcJz3WFAgh/libxml2.so.2 (0x00007fa59252d000)
	libmypaint-1.3.so.0 => /tmp/tmp.IcJz3WFAgh/libmypaint-1.3.so.0 (0x00007fa59231b000)
	libjson-c.so.2 => /tmp/tmp.IcJz3WFAgh/libjson-c.so.2 (0x00007fa592110000)
	libgobject-2.0.so.0 => /tmp/tmp.IcJz3WFAgh/libgobject-2.0.so.0 (0x00007fa591ebe000)
	libffi.so.6 => /tmp/tmp.IcJz3WFAgh/libffi.so.6 (0x00007fa591cb6000)
	libglib-2.0.so.0 => /tmp/tmp.IcJz3WFAgh/libglib-2.0.so.0 (0x00007fa5919a0000)
	libpcre.so.1 => /tmp/tmp.IcJz3WFAgh/libpcre.so.1 (0x00007fa59173e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa59151f000)
	libunwind.so.8 => /tmp/tmp.IcJz3WFAgh/libunwind.so.8 (0x00007fa591305000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa590f67000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa590d63000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa590972000)
	libXi.so.6 => /tmp/tmp.IcJz3WFAgh/libXi.so.6 (0x00007fa590762000)
	libXfixes.so.3 => /tmp/tmp.IcJz3WFAgh/libXfixes.so.3 (0x00007fa59055c000)
	libatk-bridge-2.0.so.0 => /tmp/tmp.IcJz3WFAgh/libatk-bridge-2.0.so.0 (0x00007fa59032d000)
	libwayland-client.so.0 => /tmp/tmp.IcJz3WFAgh/libwayland-client.so.0 (0x00007fa59011e000)
	libepoxy.so.0 => /tmp/tmp.IcJz3WFAgh/libepoxy.so.0 (0x00007fa58fdf2000)
	libXinerama.so.1 => /tmp/tmp.IcJz3WFAgh/libXinerama.so.1 (0x00007fa58fbef000)
	libXrandr.so.2 => /tmp/tmp.IcJz3WFAgh/libXrandr.so.2 (0x00007fa58f9e4000)
	libXcursor.so.1 => /tmp/tmp.IcJz3WFAgh/libXcursor.so.1 (0x00007fa58f7d9000)
	libXcomposite.so.1 => /tmp/tmp.IcJz3WFAgh/libXcomposite.so.1 (0x00007fa58f5d6000)
	libXdamage.so.1 => /tmp/tmp.IcJz3WFAgh/libXdamage.so.1 (0x00007fa58f3d3000)
	libxkbcommon.so.0 => /tmp/tmp.IcJz3WFAgh/libxkbcommon.so.0 (0x00007fa58f193000)
	libwayland-cursor.so.0 => /tmp/tmp.IcJz3WFAgh/libwayland-cursor.so.0 (0x00007fa58ef8b000)
	libwayland-egl.so.1 => /tmp/tmp.IcJz3WFAgh/libwayland-egl.so.1 (0x00007fa58ed89000)
	libgcab-1.0.so.0 => /tmp/tmp.IcJz3WFAgh/libgcab-1.0.so.0 (0x00007fa58eb79000)
	libsoup-2.4.so.1 => /tmp/tmp.IcJz3WFAgh/libsoup-2.4.so.1 (0x00007fa58e881000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa58e669000)
	libpng15.so.15 => /tmp/tmp.IcJz3WFAgh/libpng15.so.15 (0x00007fa58e43e000)
	libthai.so.0 => /tmp/tmp.IcJz3WFAgh/libthai.so.0 (0x00007fa58e232000)
	libfribidi.so.0 => /tmp/tmp.IcJz3WFAgh/libfribidi.so.0 (0x00007fa58e016000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa59a40f000)
	libgraphite2.so.3 => /tmp/tmp.IcJz3WFAgh/libgraphite2.so.3 (0x00007fa58dde8000)
	libXau.so.6 => /tmp/tmp.IcJz3WFAgh/libXau.so.6 (0x00007fa58dbe4000)
	libblkid.so.1 => /tmp/tmp.IcJz3WFAgh/libblkid.so.1 (0x00007fa58d9a4000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa58d61b000)
	libatspi.so.0 => /tmp/tmp.IcJz3WFAgh/libatspi.so.0 (0x00007fa58d3ea000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007fa58d19d000)
	libsqlite3.so.0 => /tmp/tmp.IcJz3WFAgh/libsqlite3.so.0 (0x00007fa58cee8000)
	libgssapi_krb5.so.2 => /tmp/tmp.IcJz3WFAgh/libgssapi_krb5.so.2 (0x00007fa58cc9b000)
	libsystemd.so.0 => /tmp/tmp.IcJz3WFAgh/libsystemd.so.0 (0x00007fa58ca6a000)
	libkrb5.so.3 => /tmp/tmp.IcJz3WFAgh/libkrb5.so.3 (0x00007fa58c781000)
	libk5crypto.so.3 => /tmp/tmp.IcJz3WFAgh/libk5crypto.so.3 (0x00007fa58c54e000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007fa58c34a000)
	libkrb5support.so.0 => /tmp/tmp.IcJz3WFAgh/libkrb5support.so.0 (0x00007fa58c13a000)
	libkeyutils.so.1 => /tmp/tmp.IcJz3WFAgh/libkeyutils.so.1 (0x00007fa58bf36000)
	libcap.so.2 => /tmp/tmp.IcJz3WFAgh/libcap.so.2 (0x00007fa58bd31000)
	liblz4.so.1 => /tmp/tmp.IcJz3WFAgh/liblz4.so.1 (0x00007fa58bb1c000)
	libgcrypt.so.11 => /tmp/tmp.IcJz3WFAgh/libgcrypt.so.11 (0x00007fa58b89b000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007fa58b686000)
	libdw.so.1 => /tmp/tmp.IcJz3WFAgh/libdw.so.1 (0x00007fa58b435000)
	libattr.so.1 => /tmp/tmp.IcJz3WFAgh/libattr.so.1 (0x00007fa58b230000)
	libelf.so.1 => /tmp/tmp.IcJz3WFAgh/libelf.so.1 (0x00007fa58b018000)

/tmp/.mount_GIMP_ArQDnFT/usr/bin/gimp.bin --pdb-compat-mode=on ""
/tmp/.mount_GIMP_ArQDnFT/usr/bin/python
/bin/bash: /tmp/tmp.IcJz3WFAgh/libtinfo.so.5: no version information available (required by /bin/bash)
DIRNAME: /tmp/.mount_GIMP_ArQDnFT/usr/bin
DESKTOPFILE_NAME: gimp.desktop
APP_FULL: GNU Image Manipulation Program
APP: GNUImageManipulationProgram
APP_FULL: GNU Image Manipulation Program
APP: GNUImageManipulationProgram
BIN: /tmp/.mount_GIMP_ArQDnFT/usr/bin/gimp.bin
DESKTOPINTEGRATION: 
File "/home/bill/.local/share/appimagekit/GNUImageManipulationProgram_no_desktopintegration" is exiting - skipping desktop integration
is_external_process: bundled process found: /tmp/.mount_GIMP_ArQDnFT/usr/bin/gimp-2.99
../babl/babl-internal.h:214 babl_log()
	WARNING: the babl installation seems broken, no extensions found in queried
BABL_PATH (/tmp/.mount_GIMP_ArQDnFT/usr/lib/babl-0.1) this means no SIMD/instructions/special case fast paths and
only slow reference conversions are available, applications might still
run but software relying on babl for conversions will be slow

Gtk-Message: 00:12:11.712: Failed to load module "canberra-gtk-module"
Gtk-Message: 00:12:11.713: Failed to load module "canberra-gtk-module"
../babl/babl-internal.h:222 babl_fatal()
	babl_format("CIE Lab double"): not found
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
/tmp/babl.gdb:1: Error in sourced command file:
No stack.
```

I'm also using these AppImage files on a laptop with Manjaro 19.0.2 (latest).
Interestingly, the version `20200401` is working there, but I had first to install `gdb` (while previous AppImage files did not need it, apparently).
However, the version immediately after (`GIMP_AppImage-git-2.99.1-20200402-x86_64.AppImage`) is not working any more on Majaro, either.
The output from the terminal is basically the same (except different random namings in `/tmp/` let's say), checked with `meld`.

I hope this helps.

I'm available for further help in debugging.

**Comment by KenLidd** [comment] 2020-04-10 16:27
FYI, the AppImage 2,99,1-20200409 will not open on my Ubuntu 18.04. The 2.10.19 AppImage of the same date works fine. When I run the 2.99.1 AppImage in terminal mode, I essentially get the same output and error messages as in the above post.

**Comment by mzannoni** [comment] 2020-04-10 16:35
I've just tried the latest 2.99.1 AppImage (with and w/o plug-ins) on my Manjaro 19.0.2, and I see the same error.
I haven't tried yet on Ubuntu 18.04.

The 2 AppImage files of the 2.10.19 from the same date are working fine, it seems.

**Comment by mzannoni** [comment] 2020-04-15 21:16
The same as above is also happening in my Ubuntu 18.04.

**Comment by KenLidd** [comment] 2020-04-17 17:46
Just downloaded the recent 2.99.1 AppImage dated 20200416 and it will not execute under Ubuntu 18.04.  The last 2.99.1 AppImage version that does execute was the 20200328 version.  However, the latest 2.10.19 AppImage (20200416) executes correctly.

**Comment by codic12** [comment] 2020-06-03 20:01
Same issue here so i have to use an old 2.99 (compiling is a pain). please get this fixed!

**Comment by hiddenman** [comment] 2020-06-05 12:19
Same problem on the latest Ubuntu 20.04 with all updates.

**Comment by Azizb750** [comment] 2020-06-07 14:54
Still the bug is unfixed:
`../babl/babl-internal.h:214`` babl_log()
	WARNING: the babl installation seems broken, no extensions found in queried
BABL_PATH (/tmp/.mount_GIMP_AqWw0Y6/usr/lib/babl-0.1) this means no SIMD/instructions/special case fast paths and
only slow reference conversions are available, applications might still
run but software relying on babl for conversions will be slow

../babl/babl-internal.h:222 babl_fatal()
	babl_format("CIE Lab double"): not found
sh: /tmp/babl.gdb: Άρνηση πρόσβασης

warning: File "/usr/lib64/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.

warning: File "/usr/lib64/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
#3  0x00007fac2cb77159 in babl_die () at ../babl/babl-internal.c:76
#4  0x00007fac2cb6e3b5 in babl_fatal (format=format@entry=0x7fac2cb9be43 "%s(\"%s\"): not found") at ../babl/babl-internal.h:224
#5  0x00007fac2cb6f528 in babl_format (name=name@entry=0x96e706 "CIE Lab double") at ../babl/babl-format.c:724
#6  0x00000000007a204e in gimp_gradient_class_init (klass=<optimized out>) at gimpgradient.c:136
#7  gimp_gradient_class_intern_init (klass=<optimized out>) at gimpgradient.c:97
#8  0x00007fac2a15732e in type_class_init_Wm (pclass=0x253df80, node=0x2603790) at gtype.c:2232
#9  g_type_class_ref (type=<optimized out>) at gtype.c:2947
#10 0x00007fac2a13d7b9 in object_set_property (nqueue=0x7fac0c001ba0, value=<optimized out>, pspec=0x2a17650, object=0x29c39b0) at gobject.c:1447
#11 g_object_new_internal (class=class@entry=0x25fdbf0, params=params@entry=0x7ffe324cf030, n_params=3) at gobject.c:1839
#12 0x00007fac2a13f251 in g_object_new_valist (object_type=<optimized out>, first_property_name=first_property_name@entry=0x8d53db "children-type", var_args=var_args@entry=0x7ffe324cf178) at gobject.c:2128
#13 0x00007fac2a13f58c in g_object_new (object_type=<optimized out>, first_property_name=first_property_name@entry=0x8d53db "children-type") at gobject.c:1648
#14 0x00000000007f3800 in gimp_list_new (children_type=39860112, unique_names=unique_names@entry=1) at gimplist.c:426
#15 0x0000000000787ee7 in gimp_data_factory_constructed (object=0x24d2150) at gimpdatafactory.c:203
#16 0x00007fac2a13d442 in g_object_new_internal (class=class@entry=0x25e7c90, params=params@entry=0x7ffe324cf550, n_params=7) at gobject.c:1845
#17 0x00007fac2a13f251 in g_object_new_valist (object_type=<optimized out>, first_property_name=first_property_name@entry=0x952f16 "gimp", var_args=var_args@entry=0x7ffe324cf698) at gobject.c:2128
#18 0x00007fac2a13f58c in g_object_new (object_type=<optimized out>, first_property_name=first_property_name@entry=0x952f16 "gimp") at gobject.c:1648
#19 0x0000000000789f36 in gimp_data_loader_factory_new (gimp=gimp@entry=0x26721a0, data_type=39860112, path_property_name=path_property_name@entry=0x96d7fb "gradient-path", writable_property_name=writable_property_name@entry=0x8d2db3 "gradient-path-writable", ext_property_name=ext_property_name@entry=0x9629f0 "gradient-paths", new_func=0x7a25c0 <gimp_gradient_new>, get_standard_func=0x7a2650 <gimp_gradient_get_standard>) at gimpdataloaderfactory.c:241
#20 0x000000000074b143 in gimp_data_factories_init (gimp=gimp@entry=0x26721a0) at gimp-data-factories.c:160
#21 0x0000000000747e1b in gimp_init (gimp=0x26721a0) at gimp.c:264
#22 0x00007fac2a159c0b in g_type_create_instance (type=<optimized out>) at gtype.c:1866
#23 0x00007fac2a13d40d in g_object_new_internal (class=class@entry=0x2608a40, params=params@entry=0x7ffe324cfb00, n_params=2) at gobject.c:1805
#24 0x00007fac2a13f251 in g_object_new_valist (object_type=<optimized out>, first_property_name=first_property_name@entry=0x93d381 "name", var_args=var_args@entry=0x7ffe324cfc48) at gobject.c:2128
#25 0x00007fac2a13f58c in g_object_new (object_type=<optimized out>, first_property_name=first_property_name@entry=0x93d381 "name") at gobject.c:1648
#26 0x0000000000748966 in gimp_new (name=name@entry=0x22c7580 "/tmp/.mount_GIMP_AqWw0Y6/usr/bin/gimp.bin", session_name=session_name@entry=0x0, default_folder=default_folder@entry=0x0, be_verbose=be_verbose@entry=0, no_data=no_data@entry=0, no_fonts=no_fonts@entry=0, no_interface=0, use_shm=1, use_cpu_accel=1, console_messages=0, show_playground=1, show_debug_menu=1, stack_trace_mode=GIMP_STACK_TRACE_QUERY, pdb_compat_mode=GIMP_PDB_COMPAT_ON) at gimp.c:611
#27 0x00000000004acd10 in app_run (full_prog_name=0x22c7580 "/tmp/.mount_GIMP_AqWw0Y6/usr/bin/gimp.bin", filenames=0x0, alternate_system_gimprc=alternate_system_gimprc@entry=0x0, alternate_gimprc=alternate_gimprc@entry=0x0, session_name=0x0, batch_interpreter=0x0, batch_commands=0x0, as_new=0, no_interface=0, no_data=0, no_fonts=0, no_splash=0, be_verbose=0, use_shm=1, use_cpu_accel=1, console_messages=0, use_debug_handler=0, show_playground=1, show_debug_menu=1, stack_trace_mode=GIMP_STACK_TRACE_QUERY, pdb_compat_mode=GIMP_PDB_COMPAT_ON, backtrace_file=0x22c3a00 "/root/.config/GIMP-AppImage/2.99/CrashLog/GIMP-crash-1591541392.txt") at app.c:244
#28 0x00000000004ac448 in main (argc=<optimized out>, argv=<optimized out>) at main.c:636
[Inferior 1 (process 2619) detached] `

**Comment by Azizb750** [comment] 2020-06-07 14:54
something brakes babl as I see

**Comment by aferrero2707** [comment] 2020-06-18 15:29
@hiddenman @Azizb750 @mzannoni @KenLidd @gsbhasin123 
Sorry for the long delay to respond to this... the times we are living are quite tough.

I think I have fixed the BABL-related issues in the 2.99 version of the AppImage, and the latest package ([this one](https://github.com/aferrero2707/gimp-appimage/releases/download/continuous/GIMP_AppImage-git-2.99.1-20200618-x86_64.AppImage) at the time of writing) starts correctly on my test system.

Would you be able to confirm?

Thanks!

**Comment by codic12** [comment] 2020-06-18 17:11
Hey @aferrero2707! No worries at all, sorry if I sounded condescending. I can confirm that appimage works [, and the x86_64_withplugins one](https://github.com/aferrero2707/gimp-appimage/releases/download/continuous/GIMP_AppImage-git-2.99.1-20200618-withplugins-x86_64.AppImage) works.

**Comment by codic12** [comment] 2020-06-18 17:18
I have however noticed a bug with the 2.99 builds (gtk3) - the green color seems to be hardcoded into sliders, regardless of what theme I choose. This is probably some setting I messed up, but it could be something when compiled as well (such as a theme with a green color applied when compiling)... this conflicts with the adapta theme unfortunately. does not happen on my copy of gimp compiled from source
will test on a new system, i'm about to do a reinstall soon anyways (since I'm one darn distrohopper).
Thank you so much for your amazing work with these appimages.

**Comment by mzannoni** [comment] 2020-06-18 17:37
Thanks a lot @aferrero2707, don't worry for the delay. You have all the right, with or without extraordinary situations, to take your time.

Anyhow, I can confirm that also here it seems fixed (I've tried on my Ubuntu 18.04 desktop and on my Manjaro 20.0.3 laptop).
I haven't done much more than opening a picture and tried a couple of random things (from painting to change bit depth to exporting to jpg). So, no idea if it's working correctly everywhere. But at least I can confirm it now starts and does things.

Edit: I guess we can close, right?

**Comment by Azizb750** [comment] 2020-06-18 19:42
Don't worry, it's normall to delay, especially with this covid-19 sh*t. Thanks a lot for fixing this critical bug. Better late than never.

**Comment by aferrero2707** [comment] 2020-06-18 20:15
@gsbhasin123 I have also noticed the green color... I will try to figure out from where it comes.

Closing this as the main issue is fixed.

**Closed as completed by aferrero2707** 2020-06-18 20:15 UTC
